export const UserData =
    [
        { "Driver": "HAM", "LapNumber": 2, "LapTime": 70.327 },
        { "Driver": "HAM", "LapNumber": 3, "LapTime": 70.182 },
        { "Driver": "HAM", "LapNumber": 4, "LapTime": 69.867 },
        { "Driver": "HAM", "LapNumber": 5, "LapTime": 69.611 },
        { "Driver": "HAM", "LapNumber": 6, "LapTime": 69.666 },
        { "Driver": "HAM", "LapNumber": 7, "LapTime": 69.689 },
        { "Driver": "HAM", "LapNumber": 8, "LapTime": 69.724 },
        { "Driver": "HAM", "LapNumber": 9, "LapTime": 69.845 },
        { "Driver": "HAM", "LapNumber": 10, "LapTime": 69.807 },
        { "Driver": "HAM", "LapNumber": 11, "LapTime": 69.956 },
        { "Driver": "HAM", "LapNumber": 12, "LapTime": 70.018 },
        { "Driver": "HAM", "LapNumber": 13, "LapTime": 69.599 },
        { "Driver": "HAM", "LapNumber": 14, "LapTime": 69.724 },
        { "Driver": "HAM", "LapNumber": 15, "LapTime": 69.809 },
        { "Driver": "HAM", "LapNumber": 16, "LapTime": 69.3 },
        { "Driver": "HAM", "LapNumber": 17, "LapTime": 69.324 },
        { "Driver": "HAM", "LapNumber": 18, "LapTime": 69.417 },
        { "Driver": "HAM", "LapNumber": 19, "LapTime": 69.507 },
        { "Driver": "HAM", "LapNumber": 20, "LapTime": 69.413 },
        { "Driver": "HAM", "LapNumber": 21, "LapTime": 69.694 },
        { "Driver": "HAM", "LapNumber": 22, "LapTime": 68.842 },
        { "Driver": "HAM", "LapNumber": 23, "LapTime": 68.932 },
        { "Driver": "HAM", "LapNumber": 24, "LapTime": 69.266 },
        { "Driver": "HAM", "LapNumber": 25, "LapTime": 69.493 },
        { "Driver": "HAM", "LapNumber": 26, "LapTime": 69.215 },
        { "Driver": "HAM", "LapNumber": 27, "LapTime": 69.8 },
        { "Driver": "HAM", "LapNumber": 28, "LapTime": 70.238 },
        { "Driver": "HAM", "LapNumber": 29, "LapTime": 69.963 },
        { "Driver": "HAM", "LapNumber": 30, "LapTime": 73.641 },
        { "Driver": "HAM", "LapNumber": 31, "LapTime": 95.141 },
        { "Driver": "HAM", "LapNumber": 32, "LapTime": 69.154 },
        { "Driver": "HAM", "LapNumber": 33, "LapTime": 69.781 },
        { "Driver": "HAM", "LapNumber": 34, "LapTime": 69.714 },
        { "Driver": "HAM", "LapNumber": 35, "LapTime": 69.361 },
        { "Driver": "HAM", "LapNumber": 36, "LapTime": 68.908 },
        { "Driver": "HAM", "LapNumber": 37, "LapTime": 68.946 },
        { "Driver": "HAM", "LapNumber": 38, "LapTime": 68.966 },
        { "Driver": "HAM", "LapNumber": 39, "LapTime": 68.733 },
        { "Driver": "HAM", "LapNumber": 40, "LapTime": 68.884 },
        { "Driver": "HAM", "LapNumber": 41, "LapTime": 68.724 },
        { "Driver": "HAM", "LapNumber": 42, "LapTime": 69.341 },
        { "Driver": "HAM", "LapNumber": 43, "LapTime": 69.276 },
        { "Driver": "HAM", "LapNumber": 44, "LapTime": 69.158 },
        { "Driver": "HAM", "LapNumber": 45, "LapTime": 69.115 },
        { "Driver": "HAM", "LapNumber": 46, "LapTime": 68.972 },
        { "Driver": "HAM", "LapNumber": 47, "LapTime": 68.955 },
        { "Driver": "HAM", "LapNumber": 48, "LapTime": 68.879 },
        { "Driver": "HAM", "LapNumber": 49, "LapTime": 68.584 },
        { "Driver": "HAM", "LapNumber": 50, "LapTime": 68.305 },
        { "Driver": "HAM", "LapNumber": 51, "LapTime": 68.872 },
        { "Driver": "HAM", "LapNumber": 52, "LapTime": 68.74 },
        { "Driver": "HAM", "LapNumber": 53, "LapTime": 68.422 },
        { "Driver": "HAM", "LapNumber": 54, "LapTime": 68.271 },
        { "Driver": "HAM", "LapNumber": 55, "LapTime": 68.478 },
        { "Driver": "HAM", "LapNumber": 56, "LapTime": 68.606 },
        { "Driver": "HAM", "LapNumber": 57, "LapTime": 68.449 },
        { "Driver": "HAM", "LapNumber": 58, "LapTime": 68.184 },
        { "Driver": "HAM", "LapNumber": 59, "LapTime": 68.23 },
        { "Driver": "HAM", "LapNumber": 60, "LapTime": 68.495 },
        { "Driver": "HAM", "LapNumber": 61, "LapTime": 68.885 },
        { "Driver": "HAM", "LapNumber": 62, "LapTime": 68.603 },
        { "Driver": "HAM", "LapNumber": 63, "LapTime": 68.256 },
        { "Driver": "HAM", "LapNumber": 64, "LapTime": 68.254 },
        { "Driver": "HAM", "LapNumber": 65, "LapTime": 68.298 },
        { "Driver": "HAM", "LapNumber": 66, "LapTime": 68.145 },
        { "Driver": "HAM", "LapNumber": 67, "LapTime": 68.406 },
        { "Driver": "HAM", "LapNumber": 68, "LapTime": 68.13 },
        { "Driver": "HAM", "LapNumber": 69, "LapTime": 68.05 },
        { "Driver": "HAM", "LapNumber": 70, "LapTime": 69.929 },
        { "Driver": "HAM", "LapNumber": 71, "LapTime": 70.417 }
    ]

export const year_data = [{ label: '2018', value: '2018' },
{ label: '2019', value: '2019' },
{ label: '2020', value: '2020' },
{ label: '2021', value: '2021' },
{ label: '2022', value: '2022' }]
export const session_data = [{ label: 'Race', value: 'Race' },
{ label: 'Qualifying', value: 'Qualifying' },
{ label: 'FP1', value: 'FP1' },
{ label: 'FP3', value: 'FP2' },
{ label: 'FP4', value: 'FP3' }]
export const gp_data =
    [{ label: 'Australian Grand Prix', value: 'Australian Grand Prix' },
    { label: 'Bahrain Grand Prix', value: 'Bahrain Grand Prix' },
    { label: 'Chinese Grand Prix', value: 'Chinese Grand Prix' },
    { label: 'Azerbaijan Grand Prix', value: 'Azerbaijan Grand Prix' },
    { label: 'Spanish Grand Prix', value: 'Spanish Grand Prix' },
    { label: 'Monaco Grand Prix', value: 'Monaco Grand Prix' },
    { label: 'Canadian Grand Prix', value: 'Canadian Grand Prix' },
    { label: 'French Grand Prix', value: 'French Grand Prix' },
    { label: 'Austrian Grand Prix', value: 'Austrian Grand Prix' },
    { label: 'British Grand Prix', value: 'British Grand Prix' },
    { label: 'German Grand Prix', value: 'German Grand Prix' },
    { label: 'Hungarian Grand Prix', value: 'Hungarian Grand Prix' },
    { label: 'Belgian Grand Prix', value: 'Belgian Grand Prix' },
    { label: 'Italian Grand Prix', value: 'Italian Grand Prix' },
    { label: 'Singapore Grand Prix', value: 'Singapore Grand Prix' },
    { label: 'Russian Grand Prix', value: 'Russian Grand Prix' },
    { label: 'Japanese Grand Prix', value: 'Japanese Grand Prix' },
    { label: 'Mexican Grand Prix', value: 'Mexican Grand Prix' },
    { label: 'United States Grand Prix', value: 'United States Grand Prix' },
    { label: 'Brazilian Grand Prix', value: 'Brazilian Grand Prix' },
    { label: 'Abu Dhabi Grand Prix', value: 'Abu Dhabi Grand Prix' }]

export const UserData2 =
    [
        { "Driver": "VER", "LapNumber": 2, "LapTime": 72.327 },
        { "Driver": "VER", "LapNumber": 3, "LapTime": 71.182 },
        { "Driver": "VER", "LapNumber": 4, "LapTime": 69.867 },
        { "Driver": "VER", "LapNumber": 5, "LapTime": 69.611 },
        { "Driver": "VER", "LapNumber": 6, "LapTime": 69.666 },
        { "Driver": "VER", "LapNumber": 7, "LapTime": 69.689 },
        { "Driver": "VER", "LapNumber": 8, "LapTime": 69.724 },
        { "Driver": "VER", "LapNumber": 9, "LapTime": 69.845 },
        { "Driver": "VER", "LapNumber": 10, "LapTime": 69.807 },
        { "Driver": "VER", "LapNumber": 11, "LapTime": 69.956 },
        { "Driver": "VER", "LapNumber": 12, "LapTime": 74.018 },
        { "Driver": "VER", "LapNumber": 13, "LapTime": 67.599 },
        { "Driver": "VER", "LapNumber": 14, "LapTime": 69.724 },
        { "Driver": "VER", "LapNumber": 15, "LapTime": 66.809 },
        { "Driver": "VER", "LapNumber": 16, "LapTime": 69.3 },
        { "Driver": "VER", "LapNumber": 17, "LapTime": 69.324 },
        { "Driver": "VER", "LapNumber": 18, "LapTime": 69.417 },
        { "Driver": "VER", "LapNumber": 19, "LapTime": 69.507 },
        { "Driver": "VER", "LapNumber": 20, "LapTime": 69.413 },
        { "Driver": "VER", "LapNumber": 21, "LapTime": 68.694 },
        { "Driver": "VER", "LapNumber": 22, "LapTime": 68.842 },
        { "Driver": "VER", "LapNumber": 23, "LapTime": 68.932 },
        { "Driver": "VER", "LapNumber": 24, "LapTime": 69.266 },
        { "Driver": "VER", "LapNumber": 25, "LapTime": 65.493 },
        { "Driver": "VER", "LapNumber": 26, "LapTime": 67.215 },
        { "Driver": "VER", "LapNumber": 27, "LapTime": 69.8 },
        { "Driver": "VER", "LapNumber": 28, "LapTime": 76.238 },
        { "Driver": "VER", "LapNumber": 29, "LapTime": 69.963 },
        { "Driver": "VER", "LapNumber": 30, "LapTime": 73.641 },
        { "Driver": "VER", "LapNumber": 31, "LapTime": 94.141 },
        { "Driver": "VER", "LapNumber": 32, "LapTime": 69.154 },
        { "Driver": "VER", "LapNumber": 33, "LapTime": 69.781 },
        { "Driver": "VER", "LapNumber": 34, "LapTime": 69.714 },
        { "Driver": "VER", "LapNumber": 35, "LapTime": 69.361 },
        { "Driver": "VER", "LapNumber": 36, "LapTime": 68.908 },
        { "Driver": "VER", "LapNumber": 37, "LapTime": 68.946 },
        { "Driver": "VER", "LapNumber": 38, "LapTime": 68.966 },
        { "Driver": "VER", "LapNumber": 39, "LapTime": 68.733 },
        { "Driver": "VER", "LapNumber": 40, "LapTime": 68.884 },
        { "Driver": "VER", "LapNumber": 41, "LapTime": 68.724 },
        { "Driver": "VER", "LapNumber": 42, "LapTime": 66.341 },
        { "Driver": "VER", "LapNumber": 43, "LapTime": 67.276 },
        { "Driver": "VER", "LapNumber": 44, "LapTime": 69.158 },
        { "Driver": "VER", "LapNumber": 45, "LapTime": 65.115 },
        { "Driver": "VER", "LapNumber": 46, "LapTime": 68.972 },
        { "Driver": "VER", "LapNumber": 47, "LapTime": 66.955 },
        { "Driver": "VER", "LapNumber": 48, "LapTime": 68.879 },
        { "Driver": "VER", "LapNumber": 49, "LapTime": 68.584 },
        { "Driver": "VER", "LapNumber": 50, "LapTime": 68.305 },
        { "Driver": "VER", "LapNumber": 51, "LapTime": 68.872 },
        { "Driver": "VER", "LapNumber": 52, "LapTime": 68.74 },
        { "Driver": "VER", "LapNumber": 53, "LapTime": 68.422 },
        { "Driver": "VER", "LapNumber": 54, "LapTime": 68.271 },
        { "Driver": "VER", "LapNumber": 55, "LapTime": 68.478 },
        { "Driver": "VER", "LapNumber": 56, "LapTime": 68.606 },
        { "Driver": "VER", "LapNumber": 57, "LapTime": 68.449 },
        { "Driver": "VER", "LapNumber": 58, "LapTime": 68.184 },
        { "Driver": "VER", "LapNumber": 59, "LapTime": 68.23 },
        { "Driver": "VER", "LapNumber": 60, "LapTime": 68.495 },
        { "Driver": "VER", "LapNumber": 61, "LapTime": 68.885 },
        { "Driver": "VER", "LapNumber": 62, "LapTime": 68.603 },
        { "Driver": "VER", "LapNumber": 63, "LapTime": 68.256 },
        { "Driver": "VER", "LapNumber": 64, "LapTime": 68.254 },
        { "Driver": "VER", "LapNumber": 65, "LapTime": 68.298 },
        { "Driver": "VER", "LapNumber": 66, "LapTime": 68.145 },
        { "Driver": "VER", "LapNumber": 67, "LapTime": 68.406 },
        { "Driver": "VER", "LapNumber": 68, "LapTime": 68.13 },
        { "Driver": "VER", "LapNumber": 69, "LapTime": 68.05 },
        { "Driver": "VER", "LapNumber": 70, "LapTime": 69.929 },
        { "Driver": "VER", "LapNumber": 71, "LapTime": 70.417 }
    ]
